const mongoose = require("mongoose");

const registerSchema = new mongoose.Schema(
  {
    name: String,
    maritalStatus: String,
    password: String,
    dob: String,
    gender: String,
    fatherName: String,
    motherName: String,
    occupationFather: String,
    occupationMother: String,
    knownLanguages: String,
    nativePlace: String,
    address: String,
    temple: String,
    presentResidence: String,
    brothers: Number,
    marriedBrothers: Number,
    sisters: Number,
    marriedSisters: Number,
    profileCreatedBy: String,
    referral: String,
    referralDetails1: { name: String, phone: String, address: String },
    referralDetails2: { name: String, phone: String, address: String },
    education: String,
    educationDetails: String,
    occupation: String,
    workDetails: String,
    workingPlace: String,
    income: String,
    height: String,
    weight: String,
    complexion: String,
    diet: String,
    specialCases: String,
    rasi: String,
    lagnam: String,
    star: String,
    dosham: String,
    birthPlace: String,
    birthTime: String,
    dasaType: String,
    horoscope: String,
    contactAddress: String,
    mobile: String,
    city: String,
    phone: String,
    state: String,
    whatsapp: String,
    district: String,
    email: String,
    country: { type: String, default: "India" },
    photo: String, // Assuming a URL or base64-encoded image
    postalCode: String,
    partnerPreference: {
      education: String,
      ageFrom: String,
      ageTo: String,
      educationDetails: String,
      jobAfterMarriage: String,
      complexion: String,
      heightFrom: String,
      heightTo: String,
      personalPreference: String,
    },
    verificationCode: String,
    termsAccepted: Boolean,
  },
  { collection: "Register" } // 👈 Ensuring data is stored in the "register" collection
);

const Register = mongoose.model("Register", registerSchema);
module.exports = Register;
