import mongoose from "mongoose";

const registerSchema = new mongoose.Schema(
  {
    name: { type: String},
    maritalStatus: { type: String},
    password: { type: String },
    dob: { type: String },
    gender: { type: String },
    email: { type: String },
    mobile: { type: String },
    fatherName: { type: String},
    motherName: { type: String },
    occupationFather: String,
    occupationMother: String,
    nativePlace: String,
    houseName: String,
    temple: String,
    presentResidence: String,
    brothers: { type: Number, min: 0, default: 0 },
    marriedBrothers: { type: Number, min: 0, default: 0 },
    sisters: { type: Number, min: 0, default: 0 },
    marriedSisters: { type: Number, min: 0, default: 0 },
    referral1Name: String,
    referral1Phone: { type: String },
    referral1Address: String,
    education: { type: String },
    educationDetails: String,
    occupation: { type: String},
    workDetails: String,
    workingPlace: String,
    income: String,
    height: String,
    weight: String,
    complexion: String,
    diet: String,
    specialCases: String,
    specialCasesDetails: String,
    rasi: String,
    lagnam: String,
    star: String,
    dosham: String,
    birthPlace: String,
    birthTime: String,
    dasaType: String,
    dasaYear: String,
    dasaMonth: String,
    dasaDay: String,
    address: String,
    city: String,
    phone: String,
    state: String,
    whatsapp: String,
    district: String,
    country: { type: String, default: "India" },
    postalCode: String,
    partnerPreference: {
      education: String,
      ageFrom: { type: String},
      ageTo: { type: String },
      educationDetails: String,
      workAfterMarriage: String,
      complexion: String,
      heightFrom: String,
      heightTo: String,
      personalPreference: String
    },
    verificationCode: String,
    termsAccepted: { type: Boolean }
  },
  { collection: "Register" } // 👈 Ensuring data is stored in the "register" collection
);

const Register = mongoose.model("Register", registerSchema);
export default Register; // Changed to ES module export
