import mongoose from "mongoose";

const registerSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    maritalStatus: { type: String, required: true },
    password: { type: String, required: true, minlength: 6 },
    dob: { type: String, required: true },
    gender: { type: String, required: true },
    email: { type: String, required: true, unique: true, match: [/\S+@\S+\.\S+/, 'Please enter a valid email'] },
    mobile: { type: String, required: true, match: [/^\d{10}$/, 'Mobile number must be 10 digits'] },
    fatherName: { type: String, required: true },
    motherName: { type: String, required: true },
    occupationFather: String,
    occupationMother: String,
    nativePlace: String,
    houseName: String,
    temple: String,
    presentResidence: String,
    brothers: { type: Number, min: 0, default: 0 },
    marriedBrothers: { type: Number, min: 0, default: 0 },
    sisters: { type: Number, min: 0, default: 0 },
    marriedSisters: { type: Number, min: 0, default: 0 },
    referral1Name: String,
    referral1Phone: { type: String, match: [/^\d{10}$/, 'Phone number must be 10 digits'] },
    referral1Address: String,
    education: { type: String, required: true },
    educationDetails: String,
    occupation: { type: String, required: true },
    workDetails: String,
    workingPlace: String,
    income: String,
    height: String,
    weight: String,
    complexion: String,
    diet: String,
    specialCases: String,
    specialCasesDetails: String,
    rasi: String,
    lagnam: String,
    star: String,
    dosham: String,
    birthPlace: String,
    birthTime: String,
    dasaType: String,
    dasaYear: String,
    dasaMonth: String,
    dasaDay: String,
    address: { type: String, required: true },
    city: String,
    phone: String,
    state: String,
    whatsapp: { type: String, match: [/^\d{10}$/, 'WhatsApp number must be 10 digits'] },
    district: String,
    country: { type: String, default: "India" },
    photo: { type: String, required: false },
    postalCode: String,
    partnerPreference: {
      education: String,
      ageFrom: { type: String, required: true },
      ageTo: { type: String, required: true },
      educationDetails: String,
      workAfterMarriage: String,
      complexion: String,
      heightFrom: String,
      heightTo: String,
      personalPreference: String
    },
    verificationCode: String,
    termsAccepted: { type: Boolean, required: true }
  },
  { collection: "Register" } // 👈 Ensuring data is stored in the "register" collection
);

const Register = mongoose.model("Register", registerSchema);
export default Register; // Changed to ES module export
